name: Run test suite

on:
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Build test container image
        run: docker build -t tsd-file-api -f "./.github/misc/containers/Dockerfile.test" .
      - name: Run all tsd-file-api tests
        run: docker run --rm tsd-file-api /bin/sh -c "python tsdfileapi/api.py & sleep 2 && python tsdfileapi/test_file_api.py"
